apiVersion: v1
kind: Secret

metadata:
  name: cloudops-secret
  namespace: cloudops

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://username:password@cluster.mongodb.net/studentdb"
  JWT_SECRET: "cloudops-super-secret-key"